name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          default: true

      - name: Activate cache
        uses: Swatinem/rust-cache@v2

      - name: Test with coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.1'
          args: '--exclude-files "tests/*" --follow-exec'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

# vim:set et sts=2:
